# Generated by Django 5.0.3 on 2024-03-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0009_alter_account_password_alter_consumer_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Password',
            field=models.TextField(max_length=255),
        ),
    ]
