# Generated by Django 5.0.3 on 2024-05-17 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0011_rename_accountname_token_accountid'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='AuthorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookstore.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='BookTypeId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookstore.booktype'),
        ),
    ]
