# Generated by Django 5.0.3 on 2024-05-19 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0012_book_active_alter_book_authorid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='Active',
            field=models.BooleanField(default=True),
        ),
    ]
