# Generated by Django 5.0.3 on 2024-06-16 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0014_account_role_alter_author_authorname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Storage Employee', 'Storage Employee'), ('Salesman', 'Salesman')], default='Admin', max_length=255),
        ),
    ]
